bash/{,root.}bashrc : added create_venv command

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -53,7 +53,7 @@ MAGENTA='\033[0;35m'
 #LIGHTMAGENTA='\033[1;35m'
 #CYAN='\033[0;36m'
 #LIGHTCYAN='\033[1;36m'
-NOCOLOUR='\033[0m'
+NO_COLOUR='\033[0m'
 USER_COLOUR="$LIGHTGRAY"
 
 # Define text styles
@@ -101,19 +101,19 @@ __setprompt() {
 	PS1="$PS1\[${YELLOW}\]$(test -n "$VIRTUAL_ENV" >> /dev/null && echo " ( $(basename "$VIRTUAL_ENV"))")"
 
 	# Skip to the next line
-	PS1="$PS1\r\n\[${USER_COLOUR}\]└─>\[${NOCOLOUR}\] "
+	PS1="$PS1\r\n\[${USER_COLOUR}\]└─>\[${NO_COLOUR}\] "
 
 	# Window title
 	PS1="$PS1\[\033]0;st (\w)\007\]"
 
 	# PS2 is used to continue a command using the \ character
-	PS2="\[${USER_COLOUR}\]>\[${NOCOLOUR}\] "
+	PS2="\[${USER_COLOUR}\]>\[${NO_COLOUR}\] "
 
 	# PS3 is used to enter a number choice in a script
 	PS3='Please enter a number from above list: '
 
 	# PS4 is used for tracing a script in debug mode
-	PS4="\[${USER_COLOUR}\]+\[${NOCOLOUR}\] "
+	PS4="\[${USER_COLOUR}\]+\[${NO_COLOUR}\] "
 }
 PROMPT_COMMAND='__setprompt' # Will run function every time a command is entered
 
@@ -170,7 +170,7 @@ command -v fgrep >> /dev/null && alias fgrep='fgrep --color=auto'
 command -v egrep >> /dev/null && alias egrep='egrep --color=auto'
 command -v diff >> /dev/null && alias diff='diff --color=auto'
 command -v ip >> /dev/null && alias ip='ip --color=auto'
-command -v wget >> /dev/null && alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"
+command -v wget >> /dev/null && alias wget='wget --hsts-file=$XDG_DATA_HOME/wget-hsts'
 # Replace default cat command
 command -v bat >> /dev/null && alias cat='bat'
 command -v ncdu >> /dev/null && alias ncdu='ncdu --color=dark'
@@ -195,12 +195,31 @@ if command -v python >> /dev/null; then
 	# Activate the python virtual environment in the current folder
 	__cmd_checker__ activate
 	activate(){
-		if [ "$1" = 'h' ]|| [ "$1" = '-h' ]|| [ "$1" = 'help' ]|| [ "$1" = '--help' ]; then
+		if [ -n "$1" ] || [ "$1" = 'h' ] || [ "$1" = '-h' ]|| [ "$1" = 'help' ]|| [ "$1" = '--help' ]; then
 			echo "Usage: activate [h|-h|help|--help] to enable the current folder's python virtual environment"
 		elif [ -f venv/Scripts/activate ]; then . venv/Scripts/activate
 		elif [ -f venv/bin/activate ]; then . venv/bin/activate
 		else echo 'Python virtual environment not detected !'; return 1
 		fi
+	}
+
+	create_venv(){
+		if [ -n "$1" ] || [ "$1" = 'h' ] || [ "$1" = '-h' ]|| [ "$1" = 'help' ]|| [ "$1" = '--help' ]; then
+			echo 'Usage: create_venv [h|-h|help|--help] to create and enable a virtual python environment'
+			return 0
+		fi
+		if [ -d venv ]; then
+			echo 'A python environment already exists'
+			return 1
+		fi
+		if [ ! -f requirements.txt ]; then
+			echo 'Cannot create venv : Missing requirements.txt file'
+			return 1
+		fi
+
+		python -m venv venv
+		activate "$@"
+		pip install -r requirements.txt
 	}
 fi
 
@@ -269,15 +288,15 @@ Available flags:
 				PACKAGE_NAME="$2"
 				echo "Package name : $PACKAGE_NAME"
 				test ! -d "$AUR_PATH/$PACKAGE_NAME" && git clone https://aur.archlinux.org/"$PACKAGE_NAME".git "$AUR_PATH"/"$PACKAGE_NAME"
-				cd "$AUR_PATH"/"$PACKAGE_NAME"
+				cd "$AUR_PATH"/"$PACKAGE_NAME" || return 1
 				GPG_KEY=$(grep validpgpkeys PKGBUILD | cut -d "'" -f 2)
 				test ! -z "$GPG_KEY" && gpg --recv-keys "$GPG_KEY"
 				makepkg -sri
-				cd -
+				cd - || return 1
 				;;
 
 			-u|u|update|--update)
-				if [ -z "$(ls $AUR_PATH)" ]; then
+				if [ -z "$(ls "$AUR_PATH")" ]; then
 					echo 'No AUR packages to update'
 					return 0
 				fi
@@ -308,7 +327,7 @@ Available flags:
 				;;
 
 			-l|l|list|--list)
-				if [ -z "$(ls $AUR_PATH)" ]; then
+				if [ -z "$(ls "$AUR_PATH")" ]; then
 					echo 'No AUR packages installed'
 					return 0
 				fi
@@ -653,11 +672,11 @@ update(){
 	command -v nvim >> /dev/null && nvim --headless -c 'lua if vim.fn.exists(":TSUpdateSync") ~= 0 then vim.cmd("TSUpdateSync") end' +q
 }
 
-__cmd_checker__ __helpme__
-__helpme__(){
+__cmd_checker__ __help_me__
+__help_me__(){
 	__cmd_checker__ print_cmd
 	print_cmd(){
-		printf "\055 ${ITALIC}%-32s${NOCOLOUR} : $2\n" "$1"
+		printf "\055 ${ITALIC}%-32s${NO_COLOUR} : $2\n" "$1"
 	}
 
 	__cmd_checker__ tprint_cmd
@@ -665,12 +684,13 @@ __helpme__(){
 		if command -v "$1" >> /dev/null; then
 			print_cmd "$1 $3" "$2"
 		#else
-		#	printf "\055 ${ITALIC}%-32s${NOCOLOUR} : ${BOLD}This command isn't enabled${NOCOLOUR}\n" "$1"
+		#	printf "\055 ${ITALIC}%-32s${NO_COLOUR} : ${BOLD}This command isn't enabled${NO_COLOUR}\n" "$1"
 		fi
 	}
 
-	echo -e "${BOLD}Available commands :${NOCOLOUR}"
+	echo -e "${BOLD}Available commands :${NO_COLOUR}"
 	tprint_cmd 'activate' 'Activate the python virtual environment'
+	tprint_cmd 'create_venv' 'Create and enable a virtual python environment'
 	tprint_cmd 'preview_csv' 'Preview a csv file' '<file>'
 	tprint_cmd 'vid' 'Shortcut to nvim diff mode' '<file1> <file2>'
 	tprint_cmd 'll' 'Detailed ls' '<directory>'
@@ -695,7 +715,7 @@ __helpme__(){
 	tprint_cmd 'sync_books' "Sync calibre's books to the linode's VPS"
 	print_cmd '?' 'Print this reminder'
 
-	echo -e "${BOLD}\nBash bang shortcuts remainders :${NOCOLOUR}"
+	echo -e "${BOLD}\nBash bang shortcuts remainders :${NO_COLOUR}"
 	print_cmd '!!' 'Last command'
 	print_cmd '!$' 'Last item ran'
 	print_cmd '!^' 'First item ran'
@@ -704,4 +724,4 @@ __helpme__(){
 	unset print_cmd tprint_cmd
 }
 __cmd_checker__ '?'
-alias '?'='__helpme__'
+alias '?'='__help_me__'
